### ISSUE TITLE
When editing my profile I cannot turn on the inspector/editor

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#160]
When I am on a form to fill out, for example, edit my profile, clicking on the EZ icon to bring up the inspector/editor, reloads the page and exists the edit screen. Is it possible to load the inspector/editor without refreshing the edit screen?

**Comment by asirota** [comment]
I'm trying to inspect a drop down menu in profile editor. Why does it reload the profile edit screen when I inspect a drop down in edit my profile?

**Comment by asirota** [comment]
It reloads back to the profile view screen when I inspect a dropdown in the edit screen. Give it a try to see what I mean. 

1. Go to your profile 
2. Edit your profile
3. Inspect any element

**Comment by mDisna** [comment]
I am unable to reproduce this. Everything is working as expected on test site.

**Comment by mDisna** [comment]
Okay, I understand now. The page needs to refresh - it would need a major overhaul to work differently.

The reason it exists the edit mode is because the profile editing screen does not have a unique URL.

Now, there are a few different options to resolve or work around this.

1. We can try we-writing the code to now require a refresh to launch the inspector
2. Or if we just need to capture the CSS path information, we can make that possible outside of the editor. For example:
    1. Add an option to the right-click context menu
    2. Write it to console on right-click

**Comment by asirota** [comment]
@mDisna and I discussed the possibility of
1) having a keyboard chord that temporarily turns off the inspector red box, and allows the buttons to be hit to proceed to the next screen

2) keep the inspector on the screen after the button is hit

3) after keyboard chord is released the red box turns on again so items on the edit form can be focused on and edited

This depends on the ability to do 1

**Comment by asirota** [comment]
This appears only when you're editing a profile but not while you're trying to register for an event or applying for a membership, so it is probably only relevant for the profile editor which makes it a lot less of an issue.
