### ISSUE TITLE
Default to selected language based on profile

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#69]
If a field in the WA profile has a language, default WATM to that language if using multilanguage

**Comment by asirota** [comment]
in this case the WA API for the client using the scope of the logged in user can be used to retrieve a field. That field name can be configured in the install script with a toggle to turn this feature on.

The default lanugage field in WA must have field selections that  field MUST match the class names defined for each language.

If there is a value mismatch or the value is null for the default language then show langauge [0] in EZ Designer by default

**Comment by mDisna** [comment]
Due to the limitations of the JavaScript Admin API, this would not be possible - however, I have added a commit ([d9ac3dc](https://github.com/NewPath-Consulting/ez-wildapricot-webdesigner/commit/d9ac3dcd97f9c901e35ab4d50c7ffdeca5e64022)) that will detect the default language of the web browser, and if a matching language is set up, it will default to that language.
